name: run-black-pytestcov
on:
  push:

# This job installs dependencies and runs tests
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Package and data setup
      run: |
        pip install -e ".[dev,docs]"
        python download_data.py

    - name: Run black style check
      run: black deepimpact --check

    - name: Run pytest with coverage
      run: pytest -q --cov=deepimpact --cov-report=term-missing

    - name: Create a build of the project
      run: python -m build

    # - name: Build Sphinx documentation
    #   run: sphinx-build -b html -W docs docs/html